#!/usr/bin/env bash
####################
# THis script transcodes the TV stream from MPEG2 to AVC.  It passes the output
# into a pipe using an MPEGTS format.  
######################################

cd "$(dirname "$0")"

library="/mnt/library"
mkdir -p $library
cd $library

TIMECODE=$( date +%y%m%d%H )

# Transcode and store as an MPEG-TS file on the disk
ffmpeg \
    -y \
    -loglevel error \
    -err_detect ignore_err \
    -i "http://HDHR-10685C23.lan:5004/auto/v7.1" \
    -t 7200 \
    -num_capture_buffers 64 \
    -c:a aac \
    -ac 2 \
    -c:v h264_v4l2m2m \
    -b:v 5M \
    -f mpegts \
    $TIMECODE.ts

# Sleep for 5 minutes to allow the HLS package to do it's work
sleep 300

# After 5 minutes, no need ot keep the ts file anymore
rm $TIMECODE.ts

