#!/usr/bin/env bash
####################
# THis script transcodes and packages the recording into an HLS format
# FOr whatever reason, directly using the hls output format causes issues
# during playback.  By temporariliy using the NUT container in the pipe, it
# seems to address it.  No idea why, but it works
######################################

TIMECODE=$( date +%y%m%d )
LIBRARY="/mnt/library"

mkdir -p $LIBRARY/$TIMECODE
cd $LIBRARY/$TIMECODE

rm *

ffmpeg \
    -y \
    -loglevel error \
    -err_detect ignore_err \
    -i "http://HDHR-10685C23.lan:5004/auto/v2.1" \
    -t 300 \
    -num_capture_buffers 64 \
    -c:a aac \
    -ac 2 \
    -c:v h264_v4l2m2m \
    -b:v 5M \
    -f nut \
    pipe: | ffmpeg \
    -f nut \
    -i pipe: \
    -c:v copy \
    -c:a copy \
    -f hls \
    -hls_time 10 \
    -hls_playlist_type event \
    out.m3u8

