#!/usr/bin/env bash
########################
# This script reads the Pipe data and packages it into an HLS format for
# streaming
###################



TEMPDIR="/tmp/localnews"
TIMECODE=$( date +%y%m%d )
LIBRARY="/mnt/library"

mkdir -p $LIBRARY

# Look for any new segments
for seg in $( ls $TEMPDIR/*.m4s | sort )
do

	# Create a folder based on the date code 
	mkdir -p $LIBRARY/$TIMECODE
	cd $LIBRARY/$TIMECODE
	# Concat the init.mp4 to the new segment and append it to the HLS recording
	ffmpeg \
		-i concat:$TEMPDIR/init.mp4\|$seg
		-c:v copy \
		-c:a copy \
		-f hls \
		-hls_time 10 \
		-hls_playlist_type event \
		-hls_flags append_list,omit_endlist \
		out.m3u8

	# Remove the segment when done
	rm $seg

done

