#!/usr/bin/env bash
########################
# This script reads the Pipe data and packages it into an HLS format for
# streaming
###################

cd "$(dirname "$0")"

SCRIPTDIR=$( pwd )

library="/mnt/library"
mkdir -p $library
cd $library


for tsfile in $( ls *.ts )
do

folder="${tsfile%.*}"

cd $folder

# TODO Package as an MP4 first to "clean up" the slop

# Start converting the video stream into an HLS video
$SCRIPTDIR/packager \
  "in=../$tsfile,stream=audio,segment_template=audio_\$Number\$.aac,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH" \
  "in=../$tsfile,stream=video,segment_template=video_\$Number\$.ts,playlist_name=video.m3u8" \
  --io_block_size 65536 \
  --segment_duration 10 \
  --hls_master_playlist_output out.m3u8 \
  --hls_playlist_type EVENT

done
